//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igrac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Igrac()
        {
            this.UcinakIgraca = new HashSet<UcinakIgraca>();
        }
    
        public int IgracId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string MjestoRodjenja { get; set; }
        public short BrojDresa { get; set; }
        public int TimId { get; set; }
        public string Pozicija { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual Tim Tim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcinakIgraca> UcinakIgraca { get; set; }
    }
}
