//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati.DbModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RezultatiEntities : DbContext
    {
        public RezultatiEntities()
            : base("name=RezultatiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Igrac> Igrac { get; set; }
        public virtual DbSet<Konferencija> Konferencija { get; set; }
        public virtual DbSet<Tim> Tim { get; set; }
        public virtual DbSet<UcinakIgraca> UcinakIgraca { get; set; }
        public virtual DbSet<Utakmica> Utakmica { get; set; }
    }
}
