//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcinakIgraca
    {
        public int UcinakId { get; set; }
        public int UtakmicaId { get; set; }
        public int IgracId { get; set; }
        public short BrojMinuta { get; set; }
        public short BrojPoena { get; set; }
        public short BrojAsistencija { get; set; }
        public short BrojSkokova { get; set; }
        public short PokusajiIzIgre { get; set; }
        public short PogodjeniSutevi { get; set; }
        public short SlobodnaBacanja { get; set; }
        public short PogodjenaBacanja { get; set; }
        public short LicneGreske { get; set; }
        public short SuteviZaTri { get; set; }
        public short PogodjeniZaTri { get; set; }
        public short UkradeneLopte { get; set; }
        public short Blokovi { get; set; }
        public short IzgubljeneLopte { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Utakmica Utakmica { get; set; }
    }
}
