//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utakmica()
        {
            this.UcinakIgraca = new HashSet<UcinakIgraca>();
        }
    
        public int UtakmicaId { get; set; }
        public System.DateTime DatumOdigravanja { get; set; }
        public int Kolo { get; set; }
        public int DomaciTimId { get; set; }
        public int GostujuciTimId { get; set; }
        public int PrvaCetvrtinaDomaci { get; set; }
        public int PrvaCetvrtinaGost { get; set; }
        public int DrugaCetvrtinaDomaci { get; set; }
        public int DrugaCetvrtinaGost { get; set; }
        public int TrecaCetvrtinaDomaci { get; set; }
        public int TrecaCetvrtinaGost { get; set; }
        public int CetvrtaCetvrtinaDomaci { get; set; }
        public int CetvrtaCetvrtinaGost { get; set; }
    
        public virtual Tim Tim { get; set; }
        public virtual Tim Tim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcinakIgraca> UcinakIgraca { get; set; }
    }
}
